### PR TITLE
Feature#107/flash styles

### PR DESCRIPTION
**Pull request by jairolan**
# Description
- I have added the css styles for the flashes.
- I have added interaction with a button using javascript.
- Removed the default helpers from the forms.
- I fixed the view renderings when saving and updating.
 
## Screenshots
Captura de pantalla_área-de-selección_20210909185310
Captura de pantalla_área-de-selección_20210909185357

### CODE REVIEW

**Review by juliocabrera820 — APPROVED** [review]
LGTM ⚡

**Review by xFerchoVJ — DISMISSED** [review]
lgtm

**Review by SampabloC — APPROVED** [review]

**Review by YilKanda — APPROVED** [review]
LGTM!

**Review by YilKanda — APPROVED** [review]
LGTM!

**Review by oramasangel — APPROVED** [review]
lgtm

**Review by JoseRicardoJimenez — APPROVED** [review]
Lgtm👍🏽

**Pull request merged**
