### PR TITLE
changing companies views design

### PR DESCRIPTION
**Pull request by oramasangel**
# Description
 - I changed the design for companies views
 - 
 Examples:
 
 # Testing
 
 Example:
  
  ## Screenshots 
after:
image

before:
image

### CODE REVIEW

**Review by brayandiazc — DISMISSED** [review]
OK

**Review by juliocabrera820 — DISMISSED** [review]

**Review by jairolan — APPROVED** [review]
Very nice design.

**Review by JoseRicardoJimenez — APPROVED** [review]
OK

**Review by brayandiazc — APPROVED** [review]
Approve

**Pull request merged**
