### PR TITLE
Fix#91/redirect user

### PR DESCRIPTION
**Pull request by juliocabrera820**
# Description

- I've fixed a problem related to redirect users
- I've added a method to redirect a user based on his role
- I've changed the procedure when a user signed in and tries to visit a restricted page

### CODE REVIEW

**Review by YilKanda — APPROVED** [review]
LGTM!

**Review by jairolan — DISMISSED** [review]
LGTM!

**Review by JoseRicardoJimenez — DISMISSED** [review]
great!

**Review by jairolan — APPROVED** [review]

**Review by JoseRicardoJimenez — APPROVED** [review]
OK

**Pull request merged**
