### PR TITLE
Feature#7/erm diagram

### PR DESCRIPTION
**Pull request by jairolan**
# Description
What did you implemented/Why did you implemented this:
- I have performed the database analysis
- I have created the entity-relationship diagram of the project
 
 # Testing
  
  ## Screenshots 
image

### CODE REVIEW

**Review by marcoswaldo — DISMISSED** [review]

**Review by oramasangel — CHANGES_REQUESTED** [review]
instead of sales table it would be providers table

**Review by JoseRicardoJimenez — APPROVED** [review]

**Review by oramasangel — APPROVED** [review]
good

**Review by oramasangel — APPROVED** [review]
GJ

**Review by jclopezdev — CHANGES_REQUESTED** [review]
Hey @jairolan! You don't need to create a new commit for each fix, you can squash all these commits in only one, I recommend you to do that, check this link or let me know by DM if you need some help
https://www.git-tower.com/learn/git/faq/git-squash/

**Review by xFerchoVJ — DISMISSED** [review]
GJ

**Review by JoseRicardoJimenez — APPROVED** [review]

**Comment by jairolan** [comment]
> Hey @jairolan! You don't need to create a new commit for each fix, you can squash all these commits in only one, I recommend you to do that, check this link or let me know in DM if you need some help
> https://www.git-tower.com/learn/git/faq/git-squash/

Thanks

**Review by jairolan — COMMENTED** [review]
thanks

**Comment by jairolan** [comment]
Thnaks

**Review by jairolan — COMMENTED** [review]
Thank you I will take it into account

**Review by YilKanda — DISMISSED** [review]
I would indicate in the relation products - providers, that many providers can also provide the same products, for example, that cereal boxes can be acquired by different providers.

But overall it looks great.

And if you need to make changes to the existing table, use this command at rails console:

`rails generate migration add_fieldname_to_tablename fieldname:string`

and

`rails db:migrate`

to run this migration.

**Review by jairolan — COMMENTED** [review]
Ok, thanks Yil

**Review by jclopezdev — APPROVED** [review]

**Review by oramasangel — APPROVED** [review]

**Review by marcoswaldo — APPROVED** [review]

**Pull request merged**
