### PR TITLE
Enhancement#26/model tests

### PR DESCRIPTION
**Pull request by juliocabrera820**
# Description
What did you implemented/Why did you implemented this:
- I've fixed a typo in a column name
- I've added new migrations
- I've made unit test in models

closes #34 
 
 # Testing 
image

### CODE REVIEW

**Review by oramasangel — APPROVED** [review]
LGTM

**Review by JoseRicardoJimenez — APPROVED** [review]
ok!

**Review by jairolan — APPROVED** [review]
Good job

**Review by SampabloC — APPROVED** [review]

**Review by YilKanda — APPROVED** [review]
LGTM!

**Pull request merged**
