### PR TITLE
Township's crud system and design

### PR DESCRIPTION
**Pull request by oramasangel**
# Description
 - I've created the structure for crud's system
 - I've designed the views
 - I've implemented calling the state names to display them in the id fields of the townships view
 
 Examples:
 
 # Testing
 
 Example:
  
  ## Screenshots

### CODE REVIEW

**Comment by brayandiazc** [comment]
LGTM

**Review by brayandiazc — APPROVED** [review]
Approve

**Review by juliocabrera820 — APPROVED** [review]
NIce job ⚡

**Review by dannharo — COMMENTED** [review]
Same comments of the other [PR](https://github.com/BC-MAY-21-ROR/proyecto-proy-t02/pull/78#pullrequestreview-741804510), restrictions in the routes and the `@states` variable in the `index` action 🤔

**Review by jairolan — APPROVED** [review]
LGTM

**Pull request merged**
